language: cpp
env:
  global:
    - secure: "Pu2hPyp3Ym3hmkW9iXVZObfE7tA3ITSaeR05VguJ9czJAMgaT7LmEN4LDoR2sQHbRAv+8QngbNUFpglzvZLIBIEefyEA39DThZptkKJ+hCUerRajfmXywSXCwPC7A1uTEY1YoUDlGvxVZA3Z7f17GFtKtDuHjLSWmrxHAM6wjK+qCweEq0umJJ+N+2DX2UpVLlWgYoknYSGipfjHRBEgPp4NRh08yvpDTFYSVQeL0qL7LbyAtkx6qhLCK6JZ2CsP3INQOoRwc8jP6VIFbuoHl3lkOzayNM49/e9wDdZ8FGqp0HjUFi7EYi/78Uvje7CrgdCiSVwoHbtAvcyPYcxu+qXzwh4AxslRL7UJtOzTbRaXfJvqt2oqtttFjD0Dk/iwnAthg7Su6UohivcUVj/9p1X1KdDbLJcoTag/MBcZP7VJDgnHjyqYwVciT1ZV0RWfuLBI584vFMTlsdzFXt384mUTCN02BOnRnw3Miq4a5irFXnDy23TdGersk7b//FPIBIhPv/wxCjUkJzTmt7ska5jACb/FHUoOyrE5mQLSVZbh/zlsIKf8yWZy7q7caowmwyPYZtAqNZWj1JmVs2c+0RmX2c76kCTHX4ocCcDx1QqV49/+R1Ah+pA7X7kcr9MklzL9z/lkAA7z5SF/UzdoGfBNicMKz5hUFixBqZ04ATw="
branches:
    only:
        - /^v\d+\..+$/
        - master
        - ci
        - travis
        - hunter
        - coverity
        - /^release.*$/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=10
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=9
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=ON
              - CUDA_VERSION=8
        - os: linux
          dist: trusty
          sudo: required
          env:
              - CUDA=OFF
        - os: osx
          osx_image: xcode9.2
          env:
              - CUDA=ON
              - CUDA_VERSION=9
        - os: osx
          osx_image: xcode9.2
          env:
              - CUDA=OFF
              - CUDA_VERSION=9
cache:
    directories:
        - $HOME/.local
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      echo "Checking format of sourcecode..."
      find . -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.cu' -o -name '*.cuh' \) -print0 | xargs -r0 clang-format -i
      git diff --color # --exit-code
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -q update
      sudo apt-get -qy install g++-6
      scripts/install_cmake.sh
      [ "$CUDA" = "ON" ] && . scripts/install-cuda-ubuntu1604.sh $CUDA_VERSION
      pyenv global 3.6
      pip install --user requests gitpython
      if [ "$CUDA_VERSION" = "8" ]; then
        sudo apt-get -qy install g++-5
        export CC=gcc-5
        export CXX=g++-5
      else
        export CC=gcc-6
        export CXX=g++-6
      fi
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      if [ "$CUDA" = "ON" ]; then
      curl -L https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda_9.2.148_mac -o $HOME/cuda_9.2.148_mac.dmg
      hdiutil mount $HOME/cuda_9.2.148_mac.dmg
      sleep 5
      ls -ltr /Volumes/CUDAMacOSXInstaller/CUDAMacOSXInstaller.app/Contents/MacOS
      sudo /Volumes/CUDAMacOSXInstaller/CUDAMacOSXInstaller.app/Contents/MacOS/CUDAMacOSXInstaller --accept-eula --no-window; export BREW_STATUS=$?
      fi
      echo "Brew status $BREW_STATUS"
      if [ $BREW_STATUS -ne 0 ]; then
        echo "Brew Failed"
        exit $BREW_STATUS
      fi
      HOMEBREW_NO_AUTO_UPDATE=1 brew install -q python3
      pip3 install -q requests gitpython
    fi
script: |
    cmake -DHUNTER_JOBS_NUMBER=4 -DCUDA=$CUDA -DOPENCL=ON -DAPI=ON -H. -Bbuild
    cmake --build build --target package -- -j4
    [ "$CUDA" = "OFF" ] && build/ethminer/ethminer --help
    if [ "$TRAVIS_OS_NAME" = linux ]; then ldd -v build/ethminer/ethminer; fi
    if [ "$TRAVIS_OS_NAME" = osx ]; then otool -L build/ethminer/ethminer; fi
    . build/ethminer/buildinfo.sh
    mkdir package
    if [ "$CUDA" = "ON" ]; then TAG=cuda-$CUDA_VERSION; else TAG=opencl; fi
    mv build/ethminer.tar.gz package/$PROJECT_NAME-$PROJECT_VERSION-$TAG-$SYSTEM_NAME-$SYSTEM_PROCESSOR.tar.gz


deploy:
  - provider: releases
    api_key:
      secure: "QPFJWi5YMdzPUMntN2OvH57of4/XF39M/H0SklUTRD/r9dd7lkWp+4vQ7KHncfYqOYzqw75wRKEcZcitjkBuwuoT8uLw6jNkB9lt3UG6J8KVWmOlKpo+D1eHC3aD0XWvRbF7q8vpeDRc08NJoLBW3AKd5jKEd8RF/6P+rc8htg9+Z162ZsUD/WjNh+gn7uMX8PVObxYueP8b1cCjHw2CVIEvgHu3vY9N9pvaoolOXxl8Px+7Zwu1S4OMP/DfcYv/sVbjshIQPhDH6YfjN1za4Ee0lP7tX0MdNzmQEOwn2IDFPZ+2DjAgQbO8HogQNtf1vfbGsVx/4J8fMWojeAjqjZqDwPat+/jLqTRalYAObdlJlO0YCH07H4jLYEHUuMGjxLs7OPJK+sSTtGhPKeaRr+3AlSkUnwrhLyPTNhX/Ja00FIslZfhoQXD/HLeiALvl0wkYXwqXuB405puwREuxSW1RmKb47QjgLxv+FNP4wXrKe9ayc+BAywXNiMCbMLPWbCr+npeeFE3L0TsXM2cVAC8j1rvWLGN861UqvsE35kudA6bnohOkSRVFoMhNfcyjXnbWaUOIUnrZS0jpAKKeC4asIjp8O+rd/9GvNU0sKMZQ+RTYJM/pMn2iOGTgV0A1OcGaRF26SRyBHpuj5gKjnSP0/qqMdeZ3WCzsq8thwWY="
    file_glob: true
    file: package/*
    skip_cleanup: true
    on:
      tags: true
